### ISSUE TITLE
Feature request: MySQL support

### ISSUE THREAD

**Issue by giovannipds** [kabudu/event-logger#1]
The title describe itself. It'd be great to also have MySQL support on the logger. Cheers!

**Comment by kabudu** [comment]
@giovannipds 

Apologies for the late response, I was out of town for a while.

As a matter of fact, I did implement MySQL support for a project of my own, but I haven't yet ported it to here. I'll aim to do this as soon as I can.

**Comment by kabudu** [comment]
@giovannipds see release [v1.1](https://github.com/kabudu/event-logger/releases/tag/v1.1) which has a MySQL storage implementation.

You will need to provide it with a MySQL PDO connection, e.g.

    $pdo = new \PDO("mysql:host=localhost;dbname=database", 'username', 'password');

    // Create the storage strategy (standalone or collection dependent on your needs)
    $storage = new \EventLogger\Storage\MySQLStorage($pdo);

    // log events
    .......

Hope this helps!

**Comment by kabudu** [comment]
Suggest you use [v1.1.1](https://github.com/kabudu/event-logger/releases/tag/v1.1.1) 

;)

**Comment by giovannipds** [comment]
Nice @kabudu, I think it's a good improvement to the package. =)
